#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  6 17:15:03 2025

@author: bmarron18
"""


# %%

'''
Hoff, 1.2.1 Est. prob of a rare event
'''

# --- Problem Statement and Prior Info --------------------------------------

    # WANT TO KNOW: fraction/% of infected in the city 
    #   == ct all infected/ct of total pop 
    #   == Y/Z == θ (true) (unk)
    
    # PRIOR INFO:
    #   θ (true) is UNK (thus a rv) with a parameter space [0,1]
    #   Other cities report/believe θ (true) == [0.05, 0.20] centered ~ 0.10


# --- Technical/Modeling Approach ---------------------------------------
    # Estimate θ (true) from a (random) sample of the city pop 
    #   ==> ct all infected in (random) sample/ct of (random) sample from pop 
    #       == y^/z^ == θ^

    # Can set z^ (sample size) but the value of  y^ is TBD (thus, a rv)
    #   z^ == 20
    # ASSUME a prob model for the rv y^ (ie, a sampling model) 
    #   ==> p(y^|θ^) == binomial dist
    
    # ASSUME a prob model for prior info about the rv θ (true) (a prior model)
    #   ==> p(θ (prior) == beta(2, 20)


# --- Outcome Space from Actual Sampling -----------------------------------------  
    # If take a sample of 20 people and the output for each person is either
    # type a or type b (entities with two possible characteristics) then there 
    # is/are 1048576 possible unique sequences (permutations) for the data
    #       ==> 2^20 == 2**20 (python)
    # The output space of unique sequences is now closed (with 1048576 ct of 
    # unique sequences)
    
    # Imagine that each of the slots/positions of the sequences are also identifiable.
    # Then there 20! arrangements for each possible unique sequence. But actually
    # realizing these arrangements (combinations) would lead to a set of the unique
    # sequences that share equal cts of type a and type b characteristics. If slot 
    # position is unimportant (ie interest is focused only on the characterics) then
    # the unique sequence in a set of combinations generated by 20! are degenerate.
    # That is they contain equal cts of type a and type b characteristics. Note that
    # all of the sets of combinations generated by 20! are symmetric about the cts 
    # of type a and type b characteristic. For example, there are 20 sequences in the
    # set where there is 1 type a and 19 type b. And symmetrically, there are 20
    # sequences in the set where there are 19 type a and 1 type b.
    
    # To find the ct of degenrate sequences in a set:
    #   1 sequence with 0 infected / 20 non-infected 
    #       == 20!/0!20! == math.comb(20,0) in python
    #   20 sequences with 1 infected / 19 non-infected
    #       == 20!/1!19! == math.comb(20,1)
    #   190 sequences with 2 infected / 18 non-infected
    #       == 20!/2!18! == math.comb(20,2)
    #   1140 sequences with 3 infected / 17 uninfected 
    #       == 20!/3!17! == math.comb(20,3)
    #   ...
    #   1140 sequences with 17 infected / 3 uninfected 
    #       == 20!/3!17! == math.comb(20,17)
    #   190 sequences with 18 infected / 2 non-infected
    #       == 20!/2!18! == math.comb(20,18)
    #   20 sequences with 19 infected / 1 non-infected
    #       == 20!/1!19! == math.comb(20,19)
    #   1 sequence with 20 infected / 0 uninfected
    #       == 20!/20!0! == math.comb(20,20)

# %%

'''
Hoff, 1.2.1 Est. prob of a rare event
(cont'd)
'''


# --- Indiv. Plots of the Sampling Model Based on Prior Info --------------------------
from pathlib import Path
import os
import math
import numpy as np
import pandas as pd
from scipy.stats import binom
from plotnine import  ggplot, aes, labs, geom_col, geom_bar, ggsave, position_dodge2

    # Binomial distro for possible values of θ
# n, p = 20, 0.05     # <== theta1.jpeg
n, p = 20, 0.10      # <== theta2.jpeg
#n, p = 20, 0.20      # <== theta3.jpeg

#x = np.arange(binom.ppf(0.01, n, p), binom.ppf(1.0, n, p))
x = np.arange(binom.ppf(0.01, n, p), binom.ppf(1.0, n, p))
y = binom.pmf(x, n, p)
df = pd.DataFrame({'x':x,'y':y})

    # plot a single dataset 
theta2 = (ggplot()
    + geom_col(df, aes(x="x", y="y"), width=0.25)    
    + labs(
        x="Infected",
        y="Prob"
    )
)

    # see plot in "Plots" window Spyder
theta2

    # saves in current working directory (/home/bmarron18)
#ggsave(theta3, "theta3.jpeg")

    # saves to ~/Desktop
doc_dir = "/home/bmarron18/Desktop"
OUTPUT_FILE = "theta2.jpeg"
output_filepath = os.path.join(doc_dir, OUTPUT_FILE)
output_f = Path(output_filepath)
ggsave(theta2, output_f)


# %%

'''
Hoff, 1.2.1 Est. prob of a rare event
(cont'd)
 https://www.sthda.com/english/wiki/ggplot2-barplots-quick-start-guide-r-software-and-data-visualization
 https://jeroenjanssens.com/plotnine/
'''


# --- Single Plot of ALL of the Sampling Models Based on Prior Info --------------------------
from pathlib import Path
import os
import math
import numpy as np
import pandas as pd
from scipy.stats import binom
from plotnine import (ggplot, aes, labs, geom_col, 
                      geom_bar, ggsave, position_dodge2,
                      scale_fill_grey, scale_colour_grey,
                      theme_bw, scale_fill_manual, scale_color_brewer)



    # quick way to set limits of x for the distro
n, p = 20, 0.10       
x = np.arange(binom.ppf(0.01, n, p), binom.ppf(1.0, n, p))

    # Binomial distro for possible values of θ
n1, p1 = 20, 0.05     # <== theta1.jpeg
n2, p2 = 20, 0.10      # <== theta2.jpeg
n3, p3 = 20, 0.20      # <== theta3.jpeg

y1 = binom.pmf(x, n1, p1)
y2 = binom.pmf(x, n2, p2)
y3 = binom.pmf(x, n3, p3)

df1 = pd.DataFrame({'x':x,'y':y1,'theta':p1})
df2 = pd.DataFrame({'x':x,'y':y2, 'theta':p2})
df3 = pd.DataFrame({'x':x,'y':y3, 'theta':p3})

combined_df = pd.concat([df1, df2, df3])

    # plot all datasets in a single graph
prior_thetas = (ggplot(combined_df, aes(x='x', y='y', fill='theta'))
#   + geom_bar(mapping=aes(x='x', y='y', fill='theta'), stat="identity",
   + geom_bar(stat="identity",
              position = position_dodge2(preserve = "single"),
               width=1.0
               )
#   + scale_colour_grey(start = 0.0, end = 0.8,)
#    + scale_fill_manual(values={'p1':'red', 'p2':'blue', 'p3':'green'})
#    + scale_color_brewer()
    + theme_bw()
    + labs(title = "Plotting Multiple Datasets",
           x = "ct Infected",
           y = "Probability")
    )



    # save in current working directory (/home/bmarron18)
#ggsave(prior_thetas, "thetas.jpeg")


    # save to ~/Desktop
doc_dir = "/home/bmarron18/Desktop"
OUTPUT_FILE = "prior_thetas.jpeg"
output_filepath = os.path.join(doc_dir, OUTPUT_FILE)
output_f = Path(output_filepath)
ggsave(prior_thetas, output_f)


# %%

'''
Hoff, 1.2.1 Est. prob of a rare event
(cont'd)
'''

import math
import numpy as np
import pandas as pd
from scipy.stats import binom, beta
from plotnine import ggplot, aes, labs, geom_line, geom_col, ggsave


# --- Plot pdf of the Prior --------------------------

a, b = 2, 20
x = np.linspace(beta.ppf(0.0, a, b), beta.ppf(1.0, a, b), 100)
#x = np.linspace(0, 1.0, 100)
y = beta.pdf(x, a, b)
df = pd.DataFrame({'x':x,'y':y})


theta_prior = (
    ggplot(df)
    + aes(x="x", y="y")
    + labs(
        x="theta",
        y="???",
    )
    + geom_line()
#    + geom_col()
)

    # see plot in "Plots" window Spyder
theta_prior

    # saves in current working directory (/home/bmarron18)
ggsave(theta_prior, "theta_prior.jpeg")


# --- Prob Calcs of the Prior --------------------------
# https://www.statology.org/how-to-use-the-beta-distribution-in-python/

    # mean
mean = beta.mean(a, b, loc=0, scale=1)
    
    
    # mode (max in pdf)
df['y'].max()       # <== the max point (y-value) in the distro
df['y'].idxmax()    # <== location (index) of the max in the df
df.loc[5]           # <== values of the x,y coords at the location
                    #   x-value is the (approx) mode
   
    # Pr (theta < 0.10)
beta.cdf(0.1, a, b, loc=0, scale=1)    
    
    
    # # Pr (0.05 < θ < 0.20)
(beta.cdf(0.2, a, b, loc=0, scale=1)) - (beta.cdf(0.05, a, b, loc=0, scale=1))



# %%















